server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-service:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user
          uri: lb://user
          predicates:
            - Path=/api/user/**
        - id: Document
          uri: lb://Document
          predicates:
            - Path=/api/document/**
        - id: Loan
          uri: lb://Loan
          predicates:
            - Path=/api/loan/**
        - id: SimulateLoan
          uri: lb://SimulateLoan
          predicates:
            - Path=/api/simulateLoan/**
        - id: CreditEvaluation
          uri: lb://CreditEvaluation
          predicates:
            - Path=/api/creditEvaluation/**
        - id: RequestTraking
          uri: lb://RequestTraking
          predicates:
            - Path=/api/requestTraking/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS 
            allowedHeaders:
              - "*"
